server:
  port: 8081
spring:
  application:
    name: ptg-portal
  datasource:
    url: jdbc:mysql://47.110.51.155:3306/ptgeer
    username: root
    password: PTGptg123
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  mybatis:
    type-aliases-package: com.ptg.pojo

  add-host-header: true #携带请求本身的head头信息